print("=== Your Adventure Simulator ===")
print("You'll be asked a bunch of questions then we'll make you up an" , "\033[31m"  ,"amazing", "\033[0m", "story with YOU as the star! ")
print()
name = input("Your name: ")
enemy = input("Your worst enemy's name: ")
superPower = input("Your super power: ")
print()
print("Our story begins as our hero name approaches a foreboding castle...")
print("Sundenly a bolt of lighening striked the ground at the feet of", name)
print("'Our final battle begins!' shouts the evil", enemy, "clearly missing the fact that", name, "has the power of", superPower, "which means they'll win quite easily")